server:
  port: 8080
spring:
  application:
    name: human-resources-management
  sleuth:
    enabled: true
  jackson:
    default-property-inclusion: always
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ukiqvpvm
    password: 1TFfGCEL4j0hhJVeZZJ0taJ6V3cneR60
    url: jdbc:postgresql://bubble.db.elephantsql.com/ukiqvpvm
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
  cache:
    redis:
      key-prefix: human-resources-management
      time-to-live: 3600
      use-key-prefix: true

management:
  tracing:
    propagation:
      type: b3
    sampling:
      probability: 1.0

keycloak:
  realm: hrm
  auth-server-url: http://localhost:8080
  resource: hrm
  ssl-required: none
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  credentials:
    secret: fxhiCGYYzAINZgO7e9G9pYqMWYMKqIEL
  public-client: true

redis:
  port: ${REDIS_PORT:6379}
  host: ${REDIS_HOST:127.0.0.1}
  database: ${REDIS_DATABASE:0}
  timeout: ${REDIS_TIMEOUT:3600}
