name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PROJECT_ID: hrm-management-2023
  IMAGE_NAME: hrm
  CLUSTER_NAME: hrm-cluster
  GAR_LOCATION: us-central1
  APP: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.1
        with:
          repository: vanhopld98/hrm

      - name: Setup JDK 11
        uses: actions/setup-java@v3.5.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build Maven
        run: |
          mvn clean install

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.6.3

      - name: Build Docker Image
        run: docker build -t hrm -f ./.github/workflows/Dockerfile . --network host

      - name: Show Docker Image
        run: docker images

#      - name: 'Google auth'
#        id: 'auth'
#        uses: 'google-github-actions/auth@v1'
#        with:
#          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
#          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: 'Build and push container'
        run: |-
            docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" ./app
            docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"
          
      - name: 'Create release name'
        run: |-
          echo "RELEASE_NAME=${{ env.APP }}-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}

      - name: 'Create Cloud Deploy release'
        uses: 'google-github-actions/create-cloud-deploy-release@v0'
        with:
          delivery_pipeline: '${{ env.APP }}'
          name: '${{ env.RELEASE_NAME }}'
          region: '${{ env.REGION }}'
          description: '${{ env.GITHUB_COMMIT_MSG }}'
          skaffold_file: 'config/skaffold.yaml'
          images: 'app=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}'


#
#      - name: Authenticate with GCP
#        uses: google-github-actions/auth@v0.6.0
#        with:
#          credentials_json: ${{ secrets.GCP_SA_KEY }}
#
##      - name: Configure Docker CLI
##        run: |
##          if ! command -v docker &> /dev/null; then
##            curl -fsSL https://get.docker.com -o get-docker.sh
##            sh get-docker.sh
##          fi
##          echo "${{ secrets.GCP_SA_KEY }}" > key.json
##          gcloud auth activate-service-account --key-file=key.json
##          gcloud auth configure-docker --quiet
#
#      - name: Push Docker Image to Container Registry
#        run: |
#          docker tag demo-app gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
#          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
#
#      - name: Deploy to GKE
#        run: |
#          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1 --project analog-memento-387714
#          kubectl apply -f .github-ci.yml
